name: Run pytohn script
on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Say Hello Mona, it's Monday"
        run: |
          echo "variable from shell environment : $env_var"
